### ISSUE TITLE
Do you have a working alpha APK somewhere?

### ISSUE THREAD

**Issue by E3V3A** [ngjoni/wvsv_corona_tracker#12]
Where to download?

**Comment by ngjoni** [comment]
Hey, this project has been forked. We are developing on this repo now: https://github.com/beat-virus/corona_tracker

We are going to publish alpha builds for iOS and android next week.

**Comment by hypery2k** [comment]
you will find more news here https://beat-virus.atlassian.net/browse/CT-48
